name: Make

on: [push, pull_request]

jobs:
  compile-hexapod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install gcc and avr-gcc
        run: |
          sudo apt update
          sudo apt install build-essential binutils gcc-avr avr-libc

      - name: Build Release
        run: |
          bin/dev/build.sh RELEASE

      - name: Run Test
        run: |
          bin/dev/test.sh

      - name: Create Archive Directory
        run: |
          bin/dev/archive.sh

      - name: Archive Artefacts
        uses: actions/upload-artifact@v4
        with:
          name: hexapodcpp
          path: archive/
